server:
  port: 8808
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka,http://peer1:8762/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    microservice-springcloud-user: /user/**
    microservice-springcloud-movie-hystrix: /movie/**
    microservice-springcloud-movie-hystrix1: /movie1/**
  ignored-services: microservice-springcloud-movie #多个用逗号分隔