server:
  port: 7903

spring:
  application:
    name: microservice-springcloud-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    datasource:
      platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  zipkin:
    base-url: http://localhost:9411
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.tommy: debug
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
foo: foo version 1
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"