server:
  port: 7901
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
spring:
  application:
    name: microservice-springcloud-movie
logging:
  level:
    com.tommy.cloud.microservicespringcloudmovie.feign.UserFeignClient: debug  #只响应debug级别