server:
  port: 7902

spring:
  application:
    name: microservice-springcloud-user
  jpa:
    generate-ddl: false
    show-sql: true
#    format_sql: true
    hibernate:
      ddl-auto: none
    datasource:
      platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.tommy: debug
# eureka.client.serviceUrl.defaultZone属性,指定服务注册中心的位置。
# 注意这里的defaultZone属性和server的defaultZone属性不是一模一样的，要加上/eureka，如果server有contextPath，则client的defaultZone属性也要加上contextPath
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}